import type { KnowledgeNote } from "./types";

const createdAt = "2026-08-17T12:00:00+09:00";

export const demoNotes: KnowledgeNote[] = [
  {
    id: "mri-brain-axial",
    slug: "mri-brain-axial",
    title: "MRI撮影断面ノート（入力サンプル）",
    summary: "ローカルプレビューで、分類・本文・確認区分の表示を確認するためのサンプルです。",
    body: "## このノートについて\n\nこれは画面確認用のサンプルで、臨床上の撮影基準は含みません。\n\n### 実際のノートに入れる項目\n\n- 対象部位と撮影目的\n- 解剖学的ランドマーク\n- 基準線と必要範囲\n- 適用条件・例外\n- 根拠資料\n\n> 実際の内容は、依頼された時に出典を確認して追加します。",
    modalities: ["MRI"],
    bodyRegions: ["頭部・脳"],
    themes: ["撮影断面・スライス設定"],
    tags: ["入力例"],
    verificationStatus: "self",
    publicationStatus: "published",
    createdAt,
    updatedAt: "2026-08-19T09:30:00+09:00",
    version: 2,
    favorite: true,
    sources: [],
    attachments: [],
  },
  {
    id: "ct-sinus-range",
    slug: "ct-sinus-range",
    title: "CT撮影範囲ノート（入力サンプル）",
    summary: "撮影範囲ノートの分類と検索を試すための、医学的内容を含まないサンプルです。",
    body: "## 記入テンプレート\n\n- 撮影目的\n- 開始位置・終了位置\n- 位置決めに使うランドマーク\n- 例外・注意点\n- 出典\n\n実際の撮影範囲はまだ登録していません。",
    modalities: ["CT"],
    bodyRegions: ["副鼻腔", "頭頸部"],
    themes: ["撮影範囲"],
    tags: ["入力例"],
    verificationStatus: "self",
    publicationStatus: "published",
    createdAt,
    updatedAt: "2026-08-18T18:10:00+09:00",
    version: 1,
    favorite: false,
    sources: [],
    attachments: [],
  },
  {
    id: "mri-knee-coronal",
    slug: "mri-knee-coronal",
    title: "根拠確認中ノート（状態サンプル）",
    summary: "根拠不足のノートを「要確認」として扱う表示サンプルです。",
    body: "## 要確認\n\n出典や適用条件を確認できるまで、このノートは下書きのままにします。",
    modalities: ["MRI"],
    bodyRegions: ["下肢"],
    themes: ["撮影断面・スライス設定"],
    tags: ["入力例", "要確認"],
    verificationStatus: "needs_review",
    publicationStatus: "draft",
    createdAt,
    updatedAt: "2026-08-17T12:45:00+09:00",
    version: 1,
    favorite: false,
    sources: [],
    attachments: [],
  },
];
